README.md, generator/generate.js, generator/mst-gql-scaffold.js
Added an option `--noReact` that prevents from generating react files.
Closes #15
=> feat: added option to not generate react scaffold

examples/1-getting-started/src/app/models/RootStore.base.ts, examples/1-getting-started/src/app/models/TodoModel.base.ts, examples/1-getting-started/src/server/schema.js, examples/2-scaffolding/src/models/RootStore.base.ts, examples/3-twitter-clone/src/app/models/RootStore.base.ts, examples/3-twitter-clone/src/server/models/RootStore.base.ts, generator/generate.js
Addresses:
https://github.com/mobxjs/mst-gql/issues/28
=> generating typescript input types

README.md
=> docs: Fix misspelling in README

src/Query.ts
This fixes the ci build and type error
=> Fix type error on query data

generator/generate.js
=> add enum to primitiveFields

generator/generate.js
=> export enum for use in typescript

generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/lib/abstractTypes/models/OwnerModelSelector.js, tests/lib/abstractTypes/models/RootStore.base.js, tests/lib/abstractTypes/models/SearchItemModelSelector.js, tests/lib/todos/models/RootStore.base.js
=> Fix missing maybeNull

examples/2-scaffolding/src/models/RootStore.base.ts, package.json, tests/lib/abstractTypes/models/RootStore.base.js, tests/lib/todos/models/RootStore.base.js
fixes some of the issues in #67
=> Update tests / examples

README.md
=> add note to readme about config

src/Query.ts
=> update initPromise to fix react-native issue

src/Query.ts
=> fix query types

src/react.tsx
=> add correct query hook type

CHANGELOG.md, generator/config.js, generator/generate.js, generator/mst-gql-scaffold.js
=> Allow field args

README.md
Oops, forgot to do this in #97
=> Update README in regards to the new `noSsr` query option from PR #97

.prettierignore, examples/2-scaffolding/mst-gql.config.js, examples/5-nextjs/README.md, examples/5-nextjs/components/todos.tsx, examples/5-nextjs/components/users.tsx, examples/5-nextjs/mst-gql.config.js, examples/5-nextjs/pages/_app.tsx, examples/5-nextjs/pages/index.tsx, examples/5-nextjs/pages/other.tsx, examples/5-nextjs/server/index.js, examples/5-nextjs/server/schema.js, examples/5-nextjs/server/store.js, examples/5-nextjs/src/models/TodoModel.ts, examples/5-nextjs/src/models/UserModel.ts, examples/5-nextjs/tsconfig.json, package.json, tests/lib/abstractTypes/models/OwnerModelSelector.js, tests/lib/abstractTypes/models/SearchItemModelSelector.js
restablish baseline formatting
=> have format command run on entire project.

generator/generate.js, generator/mst-gql-scaffold.js
Fixes #11 
Not super elegant yet. We should probably use a bit nicer logging library so we can use colors etc in the output, although that might be part of the refactor to using a proper code-generator since tools like Gluegun already contain those.
=> Log Unexpected Files

src/MSTGQLStore.ts
=> replace finally to retain old react-native support

examples/1-getting-started/src/app/models/RootStore.base.ts, examples/2-scaffolding/src/models/RootStore.base.ts, examples/3-twitter-clone/src/app/models/RootStore.base.ts, generator/generate.js
=> update how optional types are generated

README.md
=> remove experimental warning

README.md
Just corrected some random stuff I happened to see
=> correct spelling

generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/generator/generate.test.js
Also the file names for enums will now end with Type.
=> Add Type suffix to MST enums to avoid clash with TS enum name

examples/1-getting-started/src/app/components/ServerString.tsx, examples/1-getting-started/src/app/components/index.ts, examples/1-getting-started/src/app/index.tsx, examples/1-getting-started/src/app/models/RootStore.base.ts, examples/1-getting-started/src/app/models/RootStore.ts, examples/1-getting-started/src/server/schema.js, generator/generate.js
=> Generate queries with primitives

README.md
updated master >> "main" in link
=> update link to example config

generator/generate.js
=> Fix for comma between lines importing union types in RootStore.Base.ts

examples/3-twitter-clone/package.json
=> Fix ts-node-dev option in example 3

generator/generate.js
=> Union ofTypes issue fixed

package.json, src/MSTGQLObject.ts, src/MSTGQLStore.ts, src/Query.ts, src/react.tsx, yarn.lock
This PR contains a minimum set of fixes to handle package upgrades, typescript error fixes, and an unrelated bug fix. 
It does not update the examples however.  I'm hoping a regular maintainer can help out with the examples.  
I have other changes to address circular dependencies, but these are more far-reaching an need a separate PR.
=> package version upgrades, fixed TS errors, other bugs

generator/generate.js
Adds support for parameterized fields.
Fixes #272
=> Support field parameters

generator/generate.js
Properly generate `MSTGQLRef()`s for union type fields.
Fixes #304
=> Fix handling of union of root types

examples/6-scaffolding-ts-hasura/README.md, examples/6-scaffolding-ts-hasura/mst-gql.config.js, examples/6-scaffolding-ts-hasura/package.json, examples/6-scaffolding-ts-hasura/schema.graphql, examples/6-scaffolding-ts-hasura/tsconfig.json, generator/generate.js, package.json
Fixes issue with #349.
1. Some includes were not generated for field param types
2. The generated selector code needed to be updated so that it takes into account optional arguments and argument fields
These changes make the failing test in #360 work (and the generated code actually works with Hasura as well),
=> Field param generation fix

examples/6-scaffolding-ts-hasura/README.md, examples/6-scaffolding-ts-hasura/mst-gql.config.js, examples/6-scaffolding-ts-hasura/package.json, examples/6-scaffolding-ts-hasura/schema.graphql, examples/6-scaffolding-ts-hasura/tsconfig.json, package.json
examples/6-scaffolding-ts-hasura is similar to 2-scaffolding, but it
is based on Hasura generated schema for which model generation/ts
compilation fails.
This PR demonstrates the problem mentioned in PR #349
=> Add failing scaffolding example/test for the problem mentioned in #349
