examples/3-twitter-clone/src/app/models/MessageModel.base.ts, examples/3-twitter-clone/src/app/models/UserModel.base.ts, generator/generate.js
Twitter example 3 was no longer working. When scaffolding the server models, the reactUtils were generated while it shouldn't. It shouldn't be generated because '--modelsOnly' was passed to the scaffolder. 
The presence of the reactUtils causes a typescript compiler error, which blocks the server start in the Twitter example. The reactUtils couldn't be compiled by typescript because createStoreContext requires a store that is based on MSTGQLStore, which it ain't.
The fix can be found  in generate.js. The other changes are coming from the latest scaffolding output changes.
Thanks,
Derk
=> fix - example 3 twitter generated reactUtils when it shouldn't

examples/1-getting-started/src/app/models/RootStore.base.ts, examples/4-apollo-tutorial/client/src/containers/cart-item.js, examples/4-apollo-tutorial/client/src/models/RootStore.base.js, examples/4-apollo-tutorial/client/src/pages/launch.js, examples/4-apollo-tutorial/client/src/pages/launches.js, examples/4-apollo-tutorial/server/package.json, examples/4-apollo-tutorial/server/yarn.lock, src/Query.ts
This would allow for multiple queries like so:
```js
export const GET_TODOS = gql`
query UserWithTodos {
user {
id
username
fullname
}
todos {
id
name
}
}
`;
```
This is also breaking change because when using `useQuery` with react you to use the key of the query instead of `data` directly
Also unsure about the types
=> allow multiple queries

README.md, src/localStorageMixin.ts
This PR lets a use provide their own storage method to the `localStorageMixin` in case they are not in a web environment.
=> add ability to use localStorageMixin in react-native

generator/generate.js
While testing I found out that our schema sometimes does not generate an `interfaceOrUnionType` this patch simply makes that the generator does not fail when it is not defined
=> chore: [prevent_npe] prevent npe when interfaceoruniontype is null

generator/config.js, generator/generate.js, generator/mst-gql-scaffold.js
Fields with arguments are ignored by default by the generator. With
--allowFieldArgs one can have approriate definitions generated for
such fields as well.
Fixes #46
=> Add allowFieldArgs

generator/generate.js
=> don’t generate input types if format isn’t `ts`

examples/5-nextjs/components/todos.tsx, examples/5-nextjs/components/users.tsx, examples/5-nextjs/pages/index.tsx, examples/5-nextjs/server/schema.js, examples/5-nextjs/server/store.js, examples/5-nextjs/src/models/RootStore.base.ts, src/MSTGQLStore.ts, src/Query.ts, src/deflateHelper.ts, src/react.tsx
I started working on fixing #94 with my proposed solution (force fetchPolicy to 'cache-first' when on server or first render on client, and render+wait repeatedly in getDataFromTree) but found that getDataFromTree was still entering an infinite loop, since `store.query()` still pushes a promise (to store.__promises) when it's a cache hit (i.e. just getting the results from the cache, synchronously).
So it was necessary to rework the control-flow of the `Query` class, so that we only `store.pushPromise()` when there is some actual async work to do, and otherwise just set the results (`data` or `error`) and the `promise` (which is already settled). The current code in master follows a shared path of execution once it has data, regardless of whether it is from the cache or from a fresh …
=> Fix SSR issues #94 & #95 & (somewhat incidentally) bug #91

README.md, src/Query.ts, src/react.tsx, tests/lib/todos/__snapshots__/todostore.test.js.snap, tests/lib/todos/todostore.test.js
This is how I would like to resolve #99 (follow-up to issue #91 / PR #97).
Notice that none of the examples needed to be changed 😃 
I added a new snapshot test before making the changes, so you can observe the effect of this optimization via the changes to the snapshot in 34cb585
/cc @chrisdrackett @mattiasewers
=> Drop "raw" option for queries & keep __queryCache normalized (#99)

src/MSTGQLStore.ts, src/Query.ts, src/react.tsx, tests/lib/todos/todostore.test.js
As per @mweststrate's comment at https://github.com/zenflow/mst-gql/blob/4f37e7444775aeafb9b883bb2e17933937109607/src/Query.ts#L46
> // possible optimization: merge double in-flight requests
This is an important optimization when rendering a bunch of components that declare their own data dependencies, since dependencies are commonly repeated. For example, in examples/5-nextjs, in the "Todos" list, where todos are assigned to either Rick or Morty, when loading we want to request data for each of those `User`s a maximum of once. With the current code in master, when loading we have one user request per todo and therefore some duplicate requests.
I changed the public API of `RootStore` by removing `pushPromise` & `unpushPromise` and replacing them with a private `__pushPromise`. I think it …
=> [optimization] Deduplicate identical concurrent query requests

README.md, examples/1-getting-started/src/app/models/ModelBase.ts, examples/1-getting-started/src/app/models/TodoModel.base.ts, examples/2-scaffolding/src/models/AttackModel.base.ts, examples/2-scaffolding/src/models/ModelBase.ts, examples/2-scaffolding/src/models/PokemonAttackModel.base.ts, examples/2-scaffolding/src/models/PokemonDimensionModel.base.ts, examples/2-scaffolding/src/models/PokemonEvolutionRequirementModel.base.ts, examples/2-scaffolding/src/models/PokemonModel.base.ts, examples/3-twitter-clone/src/app/models/MessageModel.base.ts, examples/3-twitter-clone/src/app/models/ModelBase.ts, examples/3-twitter-clone/src/app/models/UserModel.base.ts, examples/3-twitter-clone/src/server/models/MessageModel.base.ts, examples/3-twitter-clone/src/server/models/ModelBase.ts, examples/3-twitter-clone/src/server/models/UserModel.base.ts, examples/4-apollo-tutorial/client/src/models/LaunchConnectionModel.base.js, examples/4-apollo-tutorial/client/src/models/LaunchModel.base.js, examples/4-apollo-tutorial/client/src/models/MissionModel.base.js, examples/4-apollo-tutorial/client/src/models/ModelBase.js, examples/4-apollo-tutorial/client/src/models/RocketModel.base.js, examples/4-apollo-tutorial/client/src/models/UserModel.base.js
Follow-up to #106
> I guess we can leave the remaining examples as they are, since the migration to having a ModelBase module is seamless. So only the 5-nextjs example integrates this change so far.
>    @zenflow  https://github.com/mobxjs/mst-gql/pull/106#issuecomment-535232807
Actually it's a bit of an annoyance to scaffold an example and see changes, unrelated to what I'm doing, due to the generated files not being updated yet. Also not nice to need to commit these changes in an unrelated branch.
So I went ahead and updated all the examples
/cc @chrisdrackett
=> Integrate new ModelBase file (#106) in rest of examples

.prettierignore, README.md, generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/lib/abstractTypes/models/OwnerModelSelector.js, tests/lib/abstractTypes/models/SearchItemModelSelector.js
- 5f24785 `Add XXXModelSelector module to prettier ignore` Same commit from https://github.com/mobxjs/mst-gql/pull/114#issuecomment-536592942
- 5583647 `Restore missing header/preable in generated XXXModelSelector files` Looks like [a little typo in generator.js](https://github.com/mobxjs/mst-gql/pull/115/files#diff-afe7a4325834df8a33abce88b6e9d561) was preventing these files from having the normal header for generated files
=> Restore missing header/preable in generated XXXModelSelector files

generator/generate.js, tests/generator/generate.test.js
This PR aims to solve this issue: #108.
It return an error when the user try to scaffold a model with a name reserved for graphql such as `Query, Subscription, Mutation, etc`.
Now when you try to use a graphql reserved name you will see a specific error. Ex: `"Cannot generate SubscriptionModel, Subscription is a graphql reserved name"`
To try it just see the test `handle reserved graphql name` in `generate.test.js`.
=> #108 handle naming conflict

generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/generator/generate.test.js
=> Allow LIST to be optional in TS

generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/generator/generate.test.js
I missed this during the review, but these are not actually models so I'm reverting this commit.
=> Revert "Fix enum file generation and imports"

examples/3-twitter-clone/src/app/models/RootStore.ts, package.json, src/localStorageMixin.ts, yarn.lock
closes: https://github.com/mobxjs/mst-gql/issues/224
This updates the `throttle` function in `localStorageMixin` to save with correct args. The function clears the timeout that was scheduled and re-schedules it with the latest args and the new time.
I mostly took this code from https://github.com/github/mini-throttle.
Here is an example of the two side by side and how they work:
https://codesandbox.io/s/upbeat-williamson-djyqb?file=/src/App.tsx
=> Clear timeout and schedule a new throttle with the correct args

src/Query.ts
Fix error property still containing the previous error after a successful refetch, if the initial query failed.
=> Reset error after successful query

examples/1-getting-started/src/app/models/RootStore.base.ts, examples/2-scaffolding/src/models/RootStore.base.ts, examples/3-twitter-clone/src/app/models/RootStore.base.ts, examples/3-twitter-clone/src/server/models/RootStore.base.ts, examples/4-apollo-tutorial/client/src/models/RootStore.base.js, examples/5-nextjs/src/models/RootStore.base.ts, generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/lib/abstractTypes/models/RootStore.base.js, tests/lib/todos/models/RootStore.base.js
- Adding types for the base graphql actions so they can be used to dynamically call them.
i.e. I want to call these actions from the RootStore with their string name like:
```
self[graphqlActionName](......args and stuff)
```
This currently complains about TS and doesn't have autocomplete for the possible action names I can call. This PR aims to add types so that it is possible to type these actions.
=> Base action types

examples/1-getting-started/src/app/models/RootStore.base.ts, examples/2-scaffolding/src/models/RootStore.base.ts, examples/3-twitter-clone/src/app/models/RootStore.base.ts, examples/3-twitter-clone/src/server/models/RootStore.base.ts, examples/5-nextjs/src/models/RootStore.base.ts, generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap
- Makes mutation types based on mutations instead of queries
Offending generate line that based mutation emum names on Queries: 
https://github.com/mobxjs/mst-gql/pull/234/files#diff-afe7a4325834df8a33abce88b6e9d561L683
=> Fix types for mutation enum

examples/2-scaffolding/src/models/RootStore.base.ts, generator/generate.js
- Don't create types for actions that are skipped in generation
I ran all of the examples and tests (no snapshot changes)
=> Exclude fields from type generation that we exclude in action generation

examples/3-twitter-clone/src/app/models/RootStore.base.ts, examples/3-twitter-clone/src/app/models/SearchResultModelSelector.ts, examples/3-twitter-clone/src/app/models/index.ts, examples/3-twitter-clone/src/app/models/reactUtils.ts, examples/3-twitter-clone/src/server/models/RootStore.base.ts, examples/3-twitter-clone/src/server/models/index.ts, examples/3-twitter-clone/src/server/schema.graphql, examples/3-twitter-clone/src/server/schema.ts, generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/lib/abstractTypes/models/RootStore.base.js, tests/lib/abstractTypes/models/SearchItemModelSelector.js, tests/lib/todos/models/RootStore.base.js
This PR aims to solve https://github.com/mobxjs/mst-gql/issues/255.
- Adds code generation in the `<type>ModelSelector` file for unions (unions don't generate an actual Model or Model.base file and I was following the pattern of putting the extra stuff in this file)
- Adds imports to the `<type>Union` to the `RootStore.base.ts` file for use in actions
- Adds generation to the `queryHelper` function to use the correct type if the action is using a field that is `UNION`
In order to test this out, I added an example `search` field in the twitter example (only server side right now). It uses a union type of User and Message to return results, which creates a new action in the `RootStore.base.ts`. I also tested out the generation in another project (my own) which also generates correct types.
=> Union type in actions

src/MSTGQLStore.ts
We are having issues with handling errors thrown inside a subscription. I looked around and couldn't find any suggested way of handling this. I think this simple fix would get us what we need. If there is a better way of handling these types of errors please let me know.
=> Adds onError handler to subscription

generator/generate.js, src/MSTGQLStore.ts
@chrisdrackett Sorry, this is a couple of minor fixes to follow up https://github.com/mobxjs/mst-gql/pull/261
- Returns after calling `onError` when handling a subscription message to prevent falling through to invalid code that assumes no errors
- Updates the subscription generator to allow `onError` to be passed down
=> onError Fixes

generator/mst-gql-scaffold.js
Fixes  #208
When installed with npm the `node_modules` folder has a different structure, therefore we should use the one that is common between npm and yarn.
=> Fix scaffolding on npm install

README.md, package.json, src/localStorageMixin.ts, yarn.lock
Copied from #243
Allows the user to filter which data to store in local storage
Uses lodash/pick since it allows to use dot notation for filtering nested data which is nice. But maybe there's a better alternative?
=> Add optional filter option to localStorageMixin 

src/Query.ts
This is related to the issue #273 which adds a clear method to be able to reset the query to undefined again after fetching.
=> Add clear method to Query

src/MSTGQLStore.ts
This PR exposes `gqlHttpClient` and `gqlWsClient` by moving them to `MSTGQLStore`'s volatile state and providing setter actions.
This is so either client can be initiated / changed at a later time instead of being de-referenced from the mst env.
Personally needed this because my env had an initial state that defined `gqlWsClient` as null and later initiated it when it could be provided with an authentication token. But, since the current behavior de-references the clients, reassigning it from my env would not propagate to mst-gql and it would throw an error.
=> Expose Clients for later initiation

README.md, generator/config.js, generator/generate.js, generator/mst-gql-scaffold.js, tests/config.test.js, tests/generator/__snapshots__/generate.test.js.snap, tests/generator/generate.test.js
@chrisdrackett 
Attempts to add workarounds for #223 and #92 
Adds two new scaffolding options:
`--useIdentifierNumber`: Specifying this option will use `identifierNumber` instead of `identifier` for all GQL ID types project wide. 
`--fieldOverrides gqlFieldName:gqlFieldType:mstType,...`: draws largely from the proposal in [this comment](https://github.com/mobxjs/mst-gql/issues/92#issue-493537797) The explanation in the README is hopefully sufficient, but it may need to be tweaked as its pretty verbose. The explanation is as follows:
`--fieldOverrides id:uuid:idenfitier,*:ID:identifierNumber` Overrides default MST types for matching GraphQL names and types. The format is `gqlFieldName:gqlFieldType:mstType`. Supports full or partial wildcards for fieldNames, and full wildcards for …
=> Add fieldOverrides to enable the usage of multiple and custom ID types

src/MSTGQLObject.ts, tests/lib/unionTypes/todostore.test.js
This PR contains a small fix for getting the node.id in MSTGQLRef.
**Problem:**
When I create my mobxStore from a snapshot during testing, the models do not call a setter where their id must be modified and a separator added.
```
RootStore.create({
items: {
'1': {id: '1', name: 'one'},
'2': {id: '2', name: 'two'}
},
myRef: ['1'] //  MSTGQLRef(types.late((): any => ItemModel)),
})
```
> Also, you can look real example in test https://github.com/mobxjs/mst-gql/pull/319/files#diff-8da68bbe119c10527a005b652d591c418c435a78af66333be4e4608e5fc3cc72 
I got:  `Failed to resolve reference   to late(() => ItemModel.ItemModel)`, as you can see without id becouse id in this case just empty space `''`
So, this happens because in this case not fires this code: …
=> Fix 'id' getter MSTGQLRef 

examples/2-scaffolding/package.json, package.json, src/MSTGQLStore.ts, src/Query.ts, yarn.lock
The PR bumps up `graphql-request` and introduces cancelling GraphQL requests based on changes in `graphql-request`.
=> Introduced support for AbortController in GraphQL HTTP requests

src/mergeHelper.ts
Hi all, let me introduce my idea and improvement of the current merge logic.
**Reason:**
I noticed in my application had a performance problem and memory leaks. It was because the merge logic was doing double work, long story short on each iteration of the loop, we created a model in mst and then converted the newly created model into the graphql response structure. 
For example: 
We requested 100 entities, and we got this as an array response:
```
entites: [{entity1}, {entity2}, {entity3}, ..., etc]
```
Then we would create each such entity in the `mst.map` structure, and from there convert it to an array.
Which is the bottleneck of mst as we have created a copy of the reactive data (array of entites in our case)
it starts to be noticeable when we have an array with 1000 entities in the …
=> Improving merge strategy (3х performance increase, and 5x memory allocate decrease)

generator/config.js, generator/generate.js, generator/mst-gql-scaffold.js
Fixes #362 (Should be merged after #361)
Originally for any graphql operation with arguments every formal and actual
argument has been generated into the corresponding function in
RootStore.base.ts.
Using --dynamicArgs or setting in mst-gql.config.js dynamicArgs:true
will cause generation of operation functions, which will create graphql
operations, which only define those arguments, which have a matching
variable set in "variables". This dynamic argument generation solves issues
with Hasura mutations as well.
=> Add --dynamicArgs option to generate operation arguments dynamically

examples/2-scaffolding/package.json, generator/generate.js, generator/mst-gql-scaffold.js, package.json, tests/generator/__snapshots__/generate.test.js.snap, tests/generator/generate.test.js, tests/lib/abstractTypes/models/RootStore.base.js, tests/lib/abstractTypes/models/index.js, tests/lib/unionTypes/models/RootStore.base.js, tests/lib/unionTypes/models/index.js, tests/test-cra.sh, yarn.lock
Upgrades graphql to "^16.3.0" so that it works with new CRA apps, which use webpack 5.
Added tests/test-cra.sh, which creates a new CRA app with the latest mst-gql and the necessary dependencies, checks whether generation, tsc compilation and running the app succeeds.
Fixes #365.
=> Upgrade graphql package

generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap
Queries having return type of `[String]` get scaffolded as
```typescript
queryFetchStuff(
variables?: {},
resultSelector: string | ((qb: StringModelSelector) => StringModelSelector) = stringModelPrimitives.toString(),
options: QueryOptions = {}
) {
return self.query<{ fetchStuff: StringModelType[] }>(
`query fetchStuff { fetchStuff {
${typeof resultSelector === 'function' ? resultSelector(new StringModelSelector()).toString() : resultSelector}
} }`,
variables,
options
)
},
```
treating `String` as a complex type. Obviously there is no `StringModelSelector` generated and build fails.
This change fixes that, generating proper query function.
```typescript
queryFetchStuff(variables?: {}, options: QueryOptions = {}) {
return self.query<{ fetchStuff: string[] }>(`query fetchStuff { fetchStuff …
```
=> Support [String] as query return type

generator/generate.js, tests/generator/__snapshots__/generate.test.js.snap, tests/generator/generate.test.js
This is a follow-up to #378 which added `| null` to nullable fields.
This extends support to nullable lists. When a field is of list type and is nullabble, it will be scaffolded as:
```
field?: SomeType[] | null
```
=> feat: Scaffold nullable lists as "type[] | null"
